---
baseURL: https://sol-et-co.netlify.com
languageCode: fr-fr
title: Sol &co
theme: sol-et-co
DefaultContentLanguage: fr
params:
  author: L'assembleuse
  dateFormat: Jan 2, 2006
permalinks:
  pages: "/:filename/"
taxonomies:
  category: categories
  tag: tags
related:
  threshold: 80
  includeNewer: true
  toLower: false
  indices:
  - name: prestation_key
    weight: 1
