---
baseURL: https://sol-et-co.netlify.com
languageCode: fr-fr
title: Sol & Co
theme: sol-et-co
DefaultContentLanguage: fr
params:
  author: Yop
  dateFormat: Jan 2, 2006
menu:
  footer_02:
  - url: "/mentions/"
    name: Mentions légales
    weight: 3
permalinks:
  pages: "/:filename/"
taxonomies:
  category: categories
  tag: tags
related:
  threshold: 80
  includeNewer: true
  toLower: false
  indices:
  - name: prestation_key
    weight: 1
