---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Catégories
- type: directory
  path: content/prestations
  label: Prestations
  create: documents
  match: "**/*"
  templates:
  - prestation
  - page-standard
- type: directory
  path: content/realisations
  label: Realisations
  create: documents
  match: "**/*"
  templates:
  - realisations
  - page-standard
- type: directory
  path: content/competences
  label: Competences
  create: documents
  match: "**/*"
  templates:
  - competences
  - page-standard
- type: directory
  path: content/recompenses
  label: Recompenses
  create: documents
  match: "**/*"
  templates:
  - recompenses
  - page-standard
- type: directory
  path: content/pages
  label: Pages
  create: documents
  match: "**/*"
  templates:
  - page-standard
  - page-ressources
- type: heading
  label: Qui sommes-nous
- type: directory
  path: content/approche
  label: Approche
  create: none
  match: "**/*"
  templates:
  - page-ressources
- type: directory
  path: content/historique
  label: Sol &co
  create: none
  match: "**/*"
  templates:
  - qui-sommes-nous
- type: directory
  path: content/equipe
  label: Equipe
  create: documents
  match: "**/*"
  templates:
  - equipe
- type: heading
  label: Configuration
- type: document
  path: data/global.yaml
  label: global
upload_dir: content/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
instant_preview: true
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.55.6
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
  publish_command: hugo -d public
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.55.6
  output_directory: public
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
version: 0.55.6
